# NumPy 

NumPy je matematična knjižnjica za linearno algebro, in je ena temeljev za računanje z matrikami (Array). 
Najprej vedno uvozimo z ukazom import in potem uporabljamo spremenljivko np za klice metod.

In [1]:
import numpy as np

Numpy vsebuje veliko funkcij, osredotočimo se na delo z vektorji, arrayi, matrikami.

# Numpy Array

To so vektorji (1-d polja) in matrike (2-d polja). 

## Kreiranje vektorjev in matrik (arrayev)

###  iz obstoječega seznama - List


In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
# Kreiramo array tako da pokličemo metodo array
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
mat1 = np.array(my_matrix)
print(mat1)
mat1[2,2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9

## Vgrajene metode za generacijo matrik

### arange: vrača enakom. razporejene vrednosti v intervalu


In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [35]:
# Kaksne so opcije metode arange? Preglej pomoč in preizkusi
# np.arange( ... 

### zeros in ones

In [36]:
np.zeros(3)

array([0., 0., 0.])

In [37]:
# np.zeros((5,5))

In [38]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Vrača enakomerno razporejena števila v intervalu.

In [40]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [41]:
# np.linspace(0,10,50)

## eye

Enotske matrike

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Metode za kreiranje naključnih števil.

### rand
Vrača polje naklj. števil med 0 in 1.

In [43]:
np.random.rand(2)

array([0.67705426, 0.91500411])

In [44]:
# np.random.rand(5,5)

### randn

Vrača normalno razporejena naklj. števila

In [45]:
np.random.randn(2)

array([-0.26820189,  0.40540353])

In [17]:
np.random.randn(5,5)

array([[-0.75586339, -0.1354562 ,  2.13717037,  0.08873227,  0.39763546],
       [ 0.91514881,  0.14227235,  0.50379888,  0.20313001,  0.95001401],
       [ 0.71700127, -1.37313682,  0.92823874, -0.0120876 ,  0.61200858],
       [-0.04954654, -1.53524591,  2.49517835,  2.08237713,  0.61224498],
       [ 0.45767246,  0.6394837 , -0.28436229,  0.36399255,  0.42908931]])

### randint
Naklj.števila v podanem območju

In [46]:
np.random.randint(1,100)

33

In [47]:
np.random.randint(1,100,10)

array([58, 56,  7, 95, 65, 78, 66, 26, 44, 76])

## Array : Lastnosti in metode


In [18]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [49]:
# Preglej, izpiši vrednosti v arr in randarr

In [50]:
# ranarr

## Reshape
Podamo novo obliko matrike za podane podatke.

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin
Preizkusite, kaj vračajo metode

In [21]:
ranarr.mean()

28.0

In [2]:
# ranarr.argmax()

In [3]:
# ranarr.min()

In [4]:
# ranarr.argmin()

## Shape

Shape pove obliko matrike podatkov.

In [22]:
# Vector
arr.shape

(25,)

In [23]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [24]:
arr.reshape(1,25).shape

(1, 25)

In [54]:
# Kaj dobimo ?
# arr.reshape(25,1)

In [56]:
# arr.reshape(25,1).shape

### dtype

podatkovni tip matrike.

In [75]:
arr.dtype

dtype('int64')

# Izbira in indeksiranje elementov v matrikah


## Indeksi v oglatih oklepajih

In [25]:
#Creating sample array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
#Get a value at an index
arr[8]

8

In [27]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [28]:
#Get values in a range
# arr[0:5]
# arr[:3]
# arr[3:]

## Prirejanje vrednosti elementom

In [29]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Matrike 

Format je **arr_2d[row][col]** ali **arr_2d[row,col]**. 

In [30]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
# Vrstica 1
arr_2d[1]


array([20, 25, 30])

In [32]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
# arr_2d[1][0]

In [33]:
# Getting individual element value
# arr_2d[1,0]

In [34]:
# 2D array slicing

#Shape (2,2) from top right corner
# arr_2d[:2,1:]

In [35]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [36]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

## Izbira elementov s primerjanjem



In [11]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr > 4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [41]:
bool_arr = arr>10

In [42]:
bool_arr

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [43]:
arr[bool_arr]

array([100, 100, 100, 100, 100])

In [44]:
arr[arr>2]

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [45]:
x = 2
arr[arr>x]

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Naloge

### Matematične operacije z matrikami in vektorji

Preizkusi računske operacije nad arrayem (vektorjem): seštevanje, množenje, deljenje, potenca na 2

In [18]:
# Kreiraj vektor s stevili od 1 .. 9


In [50]:
# Preizkusi računske operacije z vektorjem
arr
1/arr

/home/nbuser/anaconda3_420/lib/python3.5/site-packages/ipykernel/__main__.py:3: RuntimeWarning: divide by zero encountered in true_divide
  app.launch_new_instance()


array([       inf, 0.01      , 0.01      , 0.01      , 0.01      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

### Matematične funkcije z matrikami in vektorji
sin, cos, sqrt, log 
Kličemo jih: np.sin(array)

In [20]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [ ]:
# Preizkusi druge matematične funkcije Numpy nad vektorjem ali matrikami
# skalarni produkt, vekt.produkt, sin, cos ...

