# NumPy 

NumPy je matematična knjižnjica za linearno algebro, in je ena temeljev za računanje z matrikami (Array). 
Najprej vedno uvozimo z ukazom import in potem uporabljamo spremenljivko np za klice metod.

In [1]:
import numpy as np

Numpy vsebuje veliko funkcij, osredotočimo se na delo z vektorji, arrayi, matrikami.

# Numpy Array

To so vektorji (1-d polja) in matrike (2-d polja). 

## Kreiranje vektorjev in matrik (arrayev)

###  iz obstoječega seznama - List


In [10]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [11]:
# Kreiramo array tako da pokličemo metodo array
np.array(my_list)

array([1, 2, 3])

In [12]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
mat1 = np.array(my_matrix)
print(mat1)
mat1[2,2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9

## Vgrajene metode za generacijo matrik

### arange: vrača enakom. razporejene vrednosti v intervalu


In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
# Kaksne so opcije metode arange? Preglej pomoč in preizkusi
# np.arange( ... 

### zeros in ones

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
# np.zeros((5,5))

In [18]:
np.ones(3)

array([1., 1., 1.])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Vrača enakomerno razporejena števila v intervalu.

In [20]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
# np.linspace(0,10,50)

## eye

Enotske matrike

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Metode za kreiranje naključnih števil.

### rand
Vrača polje naklj. števil med 0 in 1.

In [23]:
np.random.rand(2)

array([0.85554783, 0.09604239])

In [24]:
# np.random.rand(5,5)

### randn

Vrača normalno razporejena naklj. števila

In [25]:
np.random.randn(2)

array([ 0.68320346, -1.71663013])

In [26]:
np.random.randn(5,5)

array([[-1.27500439,  0.0786565 , -1.05664271,  1.41517015,  0.8366323 ],
       [-1.4049426 , -0.01509813, -0.01234872, -0.74169049,  0.19174997],
       [-1.75490143, -1.20104677,  0.23290978, -0.59374887, -0.99519872],
       [ 1.99908814, -0.72670166,  0.10450167, -0.99077455,  1.06136492],
       [ 0.75850851, -0.78028463, -1.18099167, -0.46275156,  0.58234688]])

### randint
Naklj.števila v podanem območju

In [27]:
np.random.randint(1,100)

33

In [28]:
np.random.randint(1,100,10)

array([56, 58, 79, 22, 81, 67, 29, 86,  2, 54])

## Array : Lastnosti in metode


In [29]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [30]:
# Preglej, izpiši vrednosti v arr in randarr

In [31]:
# ranarr

## Reshape
Podamo novo obliko matrike za podane podatke.

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin
Preizkusite, kaj vračajo metode

In [33]:
ranarr.mean()

19.4

In [34]:
# ranarr.argmax()

In [35]:
# ranarr.min()

In [36]:
# ranarr.argmin()

## Shape

Shape pove obliko matrike podatkov.

In [37]:
# Vector
arr.shape

(25,)

In [38]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [39]:
arr.reshape(1,25).shape

(1, 25)

In [40]:
# Kaj dobimo ?
# arr.reshape(25,1)

In [41]:
# arr.reshape(25,1).shape

### dtype

podatkovni tip matrike.

In [42]:
arr.dtype

dtype(&#39;int32&#39;)

# Izbira in indeksiranje elementov v matrikah


## Indeksi v oglatih oklepajih

In [43]:
#Creating sample array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
#Get a value at an index
arr[8]

8

In [45]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [46]:
#Get values in a range
# arr[0:5]
# arr[:3]
# arr[3:]

## Prirejanje vrednosti elementom

In [47]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Matrike 

Format je **arr_2d[row][col]** ali **arr_2d[row,col]**. 

In [48]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [49]:
# Vrstica 1
arr_2d[1]


array([20, 25, 30])

In [50]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
# arr_2d[1][0]

In [51]:
# Getting individual element value
# arr_2d[1,0]

In [52]:
# 2D array slicing

#Shape (2,2) from top right corner
# arr_2d[:2,1:]

In [53]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [54]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

## Izbira elementov s primerjanjem



In [55]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [57]:
bool_arr = arr>10

In [58]:
bool_arr

array([False, False, False, False, False, False, False, False, False,
       False])

In [59]:
arr[bool_arr]

array([], dtype=int32)

In [60]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## Naloge

### Matematične operacije z matrikami in vektorji

Preizkusi računske operacije nad arrayem (vektorjem): seštevanje, množenje, deljenje, potenca na 2

In [62]:
# Kreiraj vektor s stevili od 1 .. 9


In [63]:
# Preizkusi računske operacije z vektorjem
arr
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

### Matematične funkcije z matrikami in vektorji
sin, cos, sqrt, log 
Kličemo jih: np.sin(array)

In [64]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [65]:
# Preizkusi druge matematične funkcije Numpy nad vektorjem ali matrikami
# skalarni produkt, vekt.produkt, sin, cos ...

